
// const DOMAIN = "http://0.0.0.0:3000/";
const DOMAIN = "https://www.akratiindia.in/";
const LOCALHOST = "https://www.akratiindia.in/";
// const LOCALHOST = "http://0.0.0.0:3000/";
const PAYMENT_SURL = LOCALHOST+'api/Orders/confirmOrder';
const PAYMENT_FURL = LOCALHOST+'api/Orders/orderFailed';
const MERCHANT_KEY = 'Gaba2Xqf';//'gtKFFx';
const MERCHANT_SALT = 'bE4eBZkEIV';//'eCwWELxi';
const PAYMENT_URL = 'https://secure.payu.in/_payment ';//'https://test.payu.in/_payment';
const SMS_NAME = 'Akrati';
const SMS_PASSWORD = 'kdiweod';
const SMS_API = 'http://websms.one97.net/sendsms/sms_request.php?username=';
const SMS_OTP_MESSAGE = ' is your one time password (OTP). Please use this otp to complete registration at Akratiindia.';
const AKRATI_PHONE = '9557404911';
module.exports = {
 DOMAIN : DOMAIN,
 LOCALHOST : LOCALHOST,
 MERCHANT_SALT : MERCHANT_SALT,
 MERCHANT_KEY :  MERCHANT_KEY,
 SMS_NAME : SMS_NAME,
 SMS_PASSWORD : SMS_PASSWORD,
 SMS_OTP_MESSAGE : SMS_OTP_MESSAGE,
 SMS_API : SMS_API,
 AKRATI_PHONE : AKRATI_PHONE,
 getSMSOrderAkrati: function(orderPhone,prodSize,orderTotal,date){
   var message = 'Received: Order of '+orderTotal;

     message += ' for ' + prodSize + ' items';

   message += ' from '+ orderPhone +' has to be delivered by '+date+'.';

   return message;
 },
 getSMSOrderMessage: function(prodName,prodSize,orderTotal,date){
   var message = 'Confirmed: Order for '+prodName;
   if(prodSize > 1){
     message += ' and for ' + (prodSize - 1) + ' more items';
   }
   message += ' with total of Rs.'+ orderTotal +' is successfully placed and will reach you by '+date+'.';

   return message;
},

getGenericError:function(type,code,message){
var error = new Error();
error.status = code;
error.message = message;
  return error;
},

getPaymentForm : function(responseData){
  var form = '<form action="'+PAYMENT_URL+'"  name="payuform" method=POST >'+
  '<input type="hidden" name="key" value="'+MERCHANT_KEY+'" />'+
  '<input type="hidden" name="hash_string" value="'+responseData.HashStringReq+'" />'+
  '<input type="hidden" name="hash" value="'+responseData.TransactionReqHash+'"/>'+
  '<input type="hidden" name="txnid" value="'+responseData.TransactionID+'"/>'+
  '<table>'+
  '<tr>'+
  '<td><b>Mandatory Parameters</b></td>'+
  '</tr>'+
  '<tr>'+
  '<td>Amount: </td>'+
  '<td><input name="amount"  value="'+responseData.TransactionOrderAmount+'"/></td>'+
  '<td>First Name: </td>'+
  '<td><input name="firstname" id="firstname" value="'+responseData.FirstName+'" /></td>'+
  '</tr>'+
  '<tr>'+
  '<td>Email: </td>'+
  '<td><input name="email" id="email" value="'+responseData.Email+'"  /></td>'+
  '<td>Phone: </td>'+
  '<td><input name="phone"  value="'+responseData.Phone+'"/></td>'+
  '</tr>'+
  '<tr>'+
  '<td>Product Info: </td>'+
  '<td colspan="3"><textarea name="productinfo" >'+responseData.TransactionOrderID+'</textarea>  </td>'+
  '</tr>'+
  '<tr>'+
  '<td>Success URI: </td>'+
  '<td colspan="3"><input name="surl"  size="64"  value="'+PAYMENT_SURL+'"/></td>'+
  '</tr>'+
  '<tr>'+
  '<td>Failure URI: </td>'+
  '<td colspan="3"><input name="furl"  size="64" value="'+PAYMENT_FURL+'"/></td>'+
  '</tr>'+
  '<tr>'+
'<td colspan="3"><input type="hidden" name="service_provider" value="payu_paisa" /></td>'+
'</tr>'+
  '<tr>'+
  '<td colspan="3"><input type="hidden" name="service_provider" value="" /></td>'+
  '</tr>'+
  '<tr>'+
  '<td colspan="4"><input type="submit" value="Submit"  /></td>'+
  '</tr>'+
  '</table>'+
  '</form>';

  return form;
},
  getConfirmOrderHTML : function(orderId,orderAmount,items){

  var html = '<!DOCTYPE html><html lang="en" class="js touch"><head><style type="text/css">@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate){display:none !important;}ng\:form{display:block;}.ng-animate-shim{visibility:hidden;}.ng-anchor{position:absolute;}</style> <meta charset="utf-8"/> <link rel="apple-touch-icon" sizes="76x76" href="' +LOCALHOST+ 'assets/img/apple-icon.png"> <link rel="icon" type="image/png" sizes="96x96" href="'+LOCALHOST+'assets/img/logo.png"> <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">'+
   '<title>akratiindia</title> <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"> <link href="'+LOCALHOST+'assets/css/bootstrap.css" rel="stylesheet"> <link href="'+LOCALHOST+'assets/css/gaia.css" rel="stylesheet"> <link href="'+LOCALHOST+'assets/css/login-register.css" rel="stylesheet"> <link href="'+LOCALHOST+'assets/css/animate.css" rel="stylesheet"> <link rel="stylesheet" type="text/css" href="'+LOCALHOST+'slick/slick.css"> <link rel="stylesheet" type="text/css" href="'+LOCALHOST+'slick/slick-theme.css">'+
   ' <link rel="stylesheet" type="text/css" href="'+LOCALHOST+'assets/css/roboto.css"> <link rel="stylesheet" type="text/css" href="'+LOCALHOST+'assets/css/dhtmlx.css"> <script src="'+LOCALHOST+'assets/js/dhtmlx.js"></script> <!-- Fonts and icons--> <link href="https://fonts.googleapis.com/css?family=Cambo|Poppins:400,600" rel="stylesheet" type="text/css"> <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet"> <link rel="stylesheet" href="'+LOCALHOST+'assets/css/bootstrap-datepicker.css"> <link href="'+LOCALHOST+'assets/css/fonts/pe-icon-7-stroke.css" rel="stylesheet"> <style type="text/css"></style>'+
   '</head> <body ng-app="main" ng-controller="loginCheck" id="body" class="ng-scope"> <nav class="main-header navbar navbar-default navbar-transparent navbar-fixed-top ng-scope" color-on-scroll="200" ng-class="{\'nav-opposite\':isHome!=true}" ng-controller="showProducts"> <!-- if you want to keep the navbar hidden you can add this class to the navbar "navbar-burger"--> <div class="container"> <!-- <div class="container" style="width:1268px;"> --> <div class="navbar-header"> <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar bar1" ng-class="{\'navbar-toggle-color\': isHome!=true}"></span> <span class="icon-bar bar2" ng-class="{\'navbar-toggle-color\': isHome!=true}"></span> <span class="icon-bar bar3" ng-class="{\'navbar-toggle-color\': isHome!=true}"></span> </button> <a href="'+LOCALHOST+'index.html" class="navbar-brand opaque" id="navbar-logo"> <img src="'+LOCALHOST+'assets/img/logo.png" id="topHeaderImage"> <span id="topHeaderLogo"> '+
   '<span class="logoAkrati" style="color: #0075a6;">akrati</span><span class="logoIndia" style="color: #991014;">india</span> </span> </a> </div> <div class="collapse navbar-collapse"> <ul class="nav navbar-nav navbar-right navbar-uppercase" style="margin-top:13px;"> <li class="li-search"> <div class="search-box"> <div class="container-1"> <a href="'+LOCALHOST+'#product/search="><span class="icon"><i class="fa fa-search"></i></span></a> <input type="search" id="search" my-enter="searchPressed();" ng-model="searchQuery" placeholder="Search..." class="ng-pristine ng-untouched ng-valid ng-empty"> </div> </div> </li> <li class="dropdown" onmouseover="openDropdown(this)" onmouseout="closeDropdown(this)"> <a href="" class="dropdown-toggle" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown"> <i class=""></i> Door Fitting </a> <ul class="dropdown-menu dropdown-danger"> <li> <a href="'+LOCALHOST+'#product/handles" ng-click="reloadData();"><i class=""></i> Handles</a>'+
    '</li> <li> <a href="'+LOCALHOST+'#product/Khunti" ng-click="reloadData();"><i class=""></i>Pegs/Khunti</a> </li> <li> <a href="'+LOCALHOST+'#product/Tower Bolt" ng-click="reloadData();"><i class=""></i> Tower Bolt</a> </li> <li> <a href="'+LOCALHOST+'#product/AL-Drop" ng-click="reloadData();"><i class=""></i> AL-Drop</a> </li> <li> <a href="'+LOCALHOST+'#product/Mortise" ng-click="reloadData();"><i class=""></i> Mortise</a> </li> <li> <a href="'+LOCALHOST+'#product/Bathroom Latch" ng-click="reloadData();"><i class=""></i> Bathroom Latch</a> </li> <li> <a href="'+LOCALHOST+'#product/Door Stopper" ng-click="reloadData();"><i class=""></i>Door Stopper</a> </li> <li> <a href="'+LOCALHOST+'#product/Locks" ng-click="reloadData();"><i class=""></i> Locks</a> </li> <li> <a href="'+LOCALHOST+'#product/Door Knocker" ng-click="reloadData();"><i class=""></i> Door Knocker</a> </li> <li> <a href="'+LOCALHOST+'#product/Door Kit" ng-click="reloadData();"><i class=""></i> Door Kit</a> </li> </ul> </li> <li class="dropdown" onmouseover="openDropdown(this)" onmouseout="closeDropdown(this)">'+
    '<a href="" class="dropdown-toggle" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown"> <i class=""></i> Cub Board Fitting </a> <ul class="dropdown-menu dropdown-danger"> <li> <a href="'+LOCALHOST+'#product/Cup Handles" ng-click="reloadData();"><i class=""></i> Handles</a> </li> <li> '+
   '<a href="'+LOCALHOST+'#product/Cup Khuti" ng-click="reloadData();"><i class=""></i> Pegs/Khunti</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Lock" ng-click="reloadData();"><i class=""></i> Lock</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Channel" ng-click="reloadData();"><i class=""></i> Drawer Channel</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Tower Bolt" ng-click="reloadData();"><i class=""></i> Tower Bolt</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Door Catcher" ng-click="reloadData();"><i class=""></i> Door Catcher</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Socket" ng-click="reloadData();"><i class=""></i> Socket</a> </li> </ul> </li> <li class="dropdown" onmouseover="openDropdown(this)" onmouseout="closeDropdown(this)"> <a href="" class="dropdown-toggle" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown"> <i class=""></i> Glass Fitting </a> <ul class="dropdown-menu dropdown-danger"> <li> <a href="'+LOCALHOST+'#product/Glass Handles" ng-click="reloadData();"><i class=""></i> Handles</a> </li> <li>'+
    '<a href="'+LOCALHOST+'#product/Glass Bracket" ng-click="reloadData();"><i class=""></i> Glass Bracket</a> </li> <li> <a href="'+LOCALHOST+'#product/Glass Pivot" ng-click="reloadData();"><i class=""></i> Glass Pivot</a> </li> <li> <a href="'+LOCALHOST+'#product/Glass Stand" ng-click="reloadData();"><i class=""></i> Glass Stand</a> </li> <li> <a href="'+LOCALHOST+'#product/Glass Corner" ng-click="reloadData();"><i class=""></i> Glass Corner</a> </li> <li> <a href="'+LOCALHOST+'#product/Khuti" ng-click="reloadData();"><i class=""></i> Glass Knob</a> </li> </ul> </li> <li class="dropdown" onmouseover="openDropdown(this)" onmouseout="closeDropdown(this)"> <a href="" class="dropdown-toggle" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown"> <i class=""></i> Furniture </a> <ul class="dropdown-menu dropdown-danger"> <li> <a href="'+LOCALHOST+'#product/Furniture Sofa Leg" ng-click="reloadData();"><i class=""></i> Sofa Leg</a> </li> <li> <a href="'+LOCALHOST+'#product/Furniture Drawer Fitting" ng-click="reloadData();"><i class=""></i> Drawer Fitting</a>'+
     '</li> <li> <a href="'+LOCALHOST+'#product/Furniture Cable Manager" ng-click="reloadData();"><i class=""></i> Cable Manager</a> </li> <li> <a href="'+LOCALHOST+'#product/Furniture Curten Bracket" ng-click="reloadData();"><i class=""></i> Curten Bracket</a> </li> </ul> </li> <li> <a href="'+LOCALHOST+'#product/Decoratives" ng-class="{\'nav-opposite\':isHome!=true}" class=""> Decoratives</a> </li> <li class="dropdown userIcon" id="userIcon"> <a class="dropdown-toggle" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown" style="margin-left :7px;"> <!-- <a href="javascript:void(0)" style="margin-left :7px;"> --> <i class="fa fa-user" ng-class="{\'nav-opposite\':isHome!=true}"></i> </a> <ul class="dropdown-menu dropdown-danger" id="userTools"> <li> <div class="userToolInfo"> <a href="'+LOCALHOST+'#my/profile"> <div class="userToolName"> </div> <div id="userToolEmail"></div> </a> </div> <hr> </li> <li> <a href="'+LOCALHOST+'#my/orders" ng-click="reloadData();"><i class=""></i> My Orders</a> </li> <li> '+
     '<a href="" ng-click="logOut()">Log Out</a> </li> </ul> <!-- <div class="userTools" id="userTools" style="display: none;"> <div class="arrow-up"></div> <div class="userToolInfo"> <a href="'+LOCALHOST+'#my/profile" class="dropdown-product-link"> <div class="userToolName"> </div> <div id="userToolEmail"> </div> </a> </div> <hr> <div class="userToolOrders"> <a href="'+LOCALHOST+'#my/orders" class="dropdown-product-link">My Orders</a> </div> <hr> <div class="userToolLogOut"> <a href="" ng-click="logOut()" class="dropdown-product-link">Log Out</a> </div> </div> --> </li> <li> <a href="'+LOCALHOST+'#cart" style="margin-left :7px;"> <div><i class="fa fa-cart-arrow-down" ng-class="{\'nav-opposite\':isHome!=true}"></i></div> </a> </li> <li> <span ng-class="{\'nav-opposite\':isHome!=true}" id="cartValue" class=""></span> </li> </ul> </div> </div> <!-- /.navbar-collapse --> </nav><div class="container"> <!-- Log In | Register modal --> <div class="modal fade login" id="loginModal"> <div class="modal-dialog login animated"> <div class="modal-content"> <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> '+
   '<h4 class="modal-title" style="font-family: inherit;">Login</h4> </div> <div class="modal-body ng-scope" ng-controller="loginAction"> <div class="box"> <div class="content"> <div class="error"></div> <div class="form loginBox"> <form method="post" accept-charset="UTF-8" class="ng-pristine ng-valid"> <input id="email" value="" ng-model="login.email" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="text" placeholder="Email" name="email" style="outline: none;"> <input id="password" value="" ng-model="login.password" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="password" placeholder="Password" name="password" style="outline: none;"> <input class="btn btn-default btn-login" type="button" value="Login" ng-click="userLogin()"> <!-- <div class="facebook-login-content"> <span style="text-align: center;margin-left: 48%;font-size: 1.4vw;">Or</span> <button type="button" value="Log In With Facebook" ng-click="logInFacebook()" style="border: 0;color: white;border-radius: 2px;background: rgba(0, 0, 255, 0.73);width: 100%;font-size: 1.2vw;padding: 13px;outline:none;">Log In With Facebook</button> </div> --> <span id="loginResponse"></span> </form> </div> </div> </div> <div class="box ng-scope" ng-controller="registerAction"> <div class="content registerBox" style="display:none;"> <div class="form"> <form method="post" html="{:multipart=>true}" data-remote="true" accept-charset="UTF-8" class="ng-pristine ng-valid">'+
   ' <input id="email" ng-model="register.email" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="text" placeholder="Email" name="email"> <input id="password" ng-model="register.mobile" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="text" placeholder="Mobile" name="mobile"> <input id="password" ng-model="register.password" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="password" placeholder="Password" name="password"> <input id="password_confirmation" ng-model="register.confirmPassword" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="password" placeholder="Repeat Password" name="password_confirmation"> <input class="btn btn-default btn-register" ng-click="userRegister()" type="submit" value="Create account" id="registerButton" name="commit"> <input class="login-form-control ng-pristine ng-untouched ng-valid ng-empty ng-hide" type="text" placeholder="OTP" ng-show="OTP == true" ng-model="register.otp"> <input class="btn btn-default btn-register ng-hide" ng-show="OTP == true" ng-click="submitOTP()" type="submit" value="Submit OTP" id="otpButton" name="commit"> <span id="registerResponse"></span> </form> </div> </div> </div> </div> <div class="modal-footer"> <div class="forgot login-footer"> <span>Looking to <a href="javascript: showRegisterForm();">create an account</a> ?</span> </div> <div class="forgot register-footer" style="display:none"> <span>Already have an account?</span>'+
   ' <a href="javascript: showLoginForm();">Login</a> </div> </div> </div> </div> </div> </div> <!-- Modal ends here --> <div>  <div class="order-confirm-content" ng-controller="confirmedOrder"> <div class="order-confirm-message"> <div class="confirm-tag">Order Successful</div> <div class="order-success-icon"><img src="'+LOCALHOST+'assets/img/orderSuccess.png" width = "100%" height = "92%"></div> <div class="confirm-order-id">Order ID: '+orderId+'</div> <div class="order-mail-note"> Your order is currently being processed. You will receive an order confirmation email shortly. </div> </div> <div class="order-confirm-details"> <span class="confirm-order-detail">Order Details</span> <div class="confirm-order-items" style="margin-top:10px;">Items:'+items+'</div> <div class="confirm-order-amount" style="margin-top:10px;">Total: Rs. '+orderAmount+'</div> </div> <div class="order-note"> <p><b>Note:</b> We do not demand your banking and credit card details verbally or telephonically. Please do not divulge your details to fraudsters and imposters falsely claiming to be calling on Akratiindia\'s behalf. </p> </div> </div>  </div> </div> <footer class="footer footer-big footer-color-black" data-color="black"> <div class="container"> <div class="row"> <div class="col-md-2 col-sm-3"> <div class="info"> <h5 class="title">Company</h5> <nav> <ul> <li> <a href="'+LOCALHOST+'#/">Home</a> </li> <li> <a href="'+LOCALHOST+'#aboutUs">About Us</a> </li> </ul> </nav> </div> </div> <div class="col-md-3 col-md-offset-1 col-sm-3"> <div class="info"> <h5 class="title"> Help and Support</h5> <nav> <ul> <li> <a href="'+LOCALHOST+'#contactUs">Contact Us</a> </li> <li> <a href="'+LOCALHOST+'#howWeWork">How it works</a> </li> <li> <a href="'+LOCALHOST+'#termsConditions">Terms Of Use</a> </li> <li> <a href="'+LOCALHOST+'#companyPolicy">Privacy Policy</a> '+
   '</li> <li> <a href="'+LOCALHOST+'#moneyBack">Money Back</a> </li> </ul> </nav> </div> </div> <div class="col-md-3 col-sm-3"> </div> <div class="col-md-2 col-md-offset-1 col-sm-3"> <div class="info"> <h5 class="title">Follow us on</h5> <nav> <ul> <li> <a href="https://www.facebook.com/Akrati-India-156038181607620/" class="btn btn-social btn-facebook btn-simple"> <i class="fa fa-facebook-square"></i> Facebook </a> </li> <li> <a href="https://www.linkedin.com/company-beta/13346708/admin/updates/" class="btn btn-social btn-twitter btn-simple"> <i class="fa fa-linkedin"></i> LinkedIn </a> </li> <li> <a href="https://business.google.com/b/107704939304271578825/dashboard/l/18079967296478228732?hl=en-GB" class="btn btn-social btn-reddit btn-simple"> <i class="fa fa-google-plus-square"></i> Google+ </a> </li> </ul> </nav> </div> </div> </div> <hr> <div class="copyright"> © <script> document.write(new Date().getFullYear()) </script>2017 Akratiindia </div> </div> </footer>'+
   ' <!-- core js files --> <script src="'+LOCALHOST+'assets/js/spin.min.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/jquery.min.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/bootstrap.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/login-register.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/bootstrap-notify.min.js" type="text/javascript"></script> <script type="text/javascript" src="'+LOCALHOST+'slick/slick.js"></script> <!-- js library for devices recognition --> <script type="text/javascript" src="'+LOCALHOST+'assets/js/modernizr.js"></script> <!-- script for google maps --> <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script> <!-- script for image slider--> <!-- file where we handle all the script from the Gaia - Bootstrap Template --> <script type="text/javascript" src="'+LOCALHOST+'assets/js/gaia.js"></script> <script src="'+LOCALHOST+'assets/angular/angular.min.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/angular/ngStorage.min.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/angular/angular-route.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/angular/main.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/angular/user.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/bootstrap-datepicker.js"></script> </body></html>';

  return html;

},



getOrderFailedHTML : function(){
  // var html = '<!DOCTYPE html><html lang="en" class="js touch"><head><style type="text/css">@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate){display:none !important;}ng\:form{display:block;}.ng-animate-shim{visibility:hidden;}.ng-anchor{position:absolute;}</style> <meta charset="utf-8"/> <link rel="apple-touch-icon" sizes="76x76" href="' +LOCALHOST+ 'assets/img/apple-icon.png"> <link rel="icon" type="image/png" sizes="96x96" href="'+LOCALHOST+'assets/img/logo.png"> <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">'+
  //  '<title>akratiindia</title> <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"> <link href="'+LOCALHOST+'assets/css/bootstrap.css" rel="stylesheet"> <link href="'+LOCALHOST+'assets/css/gaia.css" rel="stylesheet"> <link href="'+LOCALHOST+'assets/css/login-register.css" rel="stylesheet"> <link href="'+LOCALHOST+'assets/css/animate.css" rel="stylesheet"> <link rel="stylesheet" type="text/css" href="'+LOCALHOST+'slick/slick.css"> <link rel="stylesheet" type="text/css" href="'+LOCALHOST+'slick/slick-theme.css">'+
  //  ' <link rel="stylesheet" type="text/css" href="'+LOCALHOST+'assets/css/roboto.css"> <link rel="stylesheet" type="text/css" href="'+LOCALHOST+'assets/css/dhtmlx.css"> <script src="'+LOCALHOST+'assets/js/dhtmlx.js"></script> <!-- Fonts and icons--> <link href="https://fonts.googleapis.com/css?family=Cambo|Poppins:400,600" rel="stylesheet" type="text/css"> <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet"> <link rel="stylesheet" href="'+LOCALHOST+'assets/css/bootstrap-datepicker.css"> <link href="'+LOCALHOST+'assets/css/fonts/pe-icon-7-stroke.css" rel="stylesheet"> <style type="text/css"></style>'+
  //  '</head> <body ng-app="main" ng-controller="loginCheck" id="body" class="ng-scope"> <nav class="navbar navbar-default navbar-transparent navbar-fixed-top ng-scope nav-opposite" color-on-scroll="200" ng-class="{\'nav-opposite\':isHome!=true}" ng-controller="showProducts"> <!-- if you want to keep the navbar hidden you can add this class to the navbar "navbar-burger"--> <div class="container" style="width:1268px;"> '+
  //  '<div class="navbar-header"> <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar bar1 navbar-toggle-color" ng-class="{\'navbar-toggle-color\': isHome!=true}"></span> <span class="icon-bar bar2 navbar-toggle-color" ng-class="{\'navbar-toggle-color\': isHome!=true}"></span> <span class="icon-bar bar3 navbar-toggle-color" ng-class="{\'navbar-toggle-color\': isHome!=true}"></span> </button> <a href="'+LOCALHOST+'index.html" class="navbar-brand opaque" id="navbar-logo"> <img src="'+LOCALHOST+'assets/img/logo.png" id="topHeaderImage"> <span id="topHeaderLogo"> <span class="logoAkrati" style="color: #0075a6;">akrati</span><span class="logoIndia" style="color: #991014;">india</span> </span> </a> </div> <div class="collapse navbar-collapse"> <ul class="nav navbar-nav navbar-right navbar-uppercase" style="margin-top:13px;"> <li> <div class="search-box"> <div class="container-1"> <a href="'+LOCALHOST+'#product/search="><span class="icon"><i class="fa fa-search"></i></span></a> <input type="search" id="search" my-enter="searchPressed();" ng-model="searchQuery" placeholder="Search..." class="ng-pristine ng-untouched ng-valid ng-empty"> </div> </div> </li> <li class="dropdown" onmouseover="openDropdown(this)" onmouseout="closeDropdown(this)"> <a href="" class="dropdown-toggle nav-opposite" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown"> '+
  //  '<i class=""></i> Door Fitting </a> <ul class="dropdown-menu dropdown-danger"> <li> <a href="'+LOCALHOST+'#product/handles" ng-click="reloadData();"><i class=""></i> Handles</a> </li> <li> <a href="'+LOCALHOST+'#product/Khunti" ng-click="reloadData();"><i class=""></i>Pegs/Khunti</a> </li> <li> <a href="'+LOCALHOST+'#product/Tower Bolt" ng-click="reloadData();"><i class=""></i> Tower Bolt</a> </li> <li> <a href="'+LOCALHOST+'#product/AL-Drop" ng-click="reloadData();"><i class=""></i> AL-Drop</a> </li> <li> <a href="'+LOCALHOST+'#product/Mortise" ng-click="reloadData();"><i class=""></i> Mortise</a> </li> <li> <a href="'+LOCALHOST+'#product/Bathroom Latch" ng-click="reloadData();"><i class=""></i> Bathroom Latch</a> </li> <li> <a href="'+LOCALHOST+'#product/Door Stopper" ng-click="reloadData();"><i class=""></i>Door Stopper</a> </li> <li> <a href="'+LOCALHOST+'#product/Locks" ng-click="reloadData();"><i class=""></i> Locks</a> </li> <li> <a href="'+LOCALHOST+'#product/Door Knocker" ng-click="reloadData();"><i class=""></i> Door Knocker</a> </li> <li> <a href="'+LOCALHOST+'#product/Door Kit" ng-click="reloadData();"><i class=""></i> Door Kit</a> </li> </ul> </li> <li class="dropdown" onmouseover="openDropdown(this)" onmouseout="closeDropdown(this)"> <a href="" class="dropdown-toggle nav-opposite" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown"> <i class=""></i> Cub Board Fitting </a> <ul class="dropdown-menu dropdown-danger"> <li>'+
  //  ' <a href="'+LOCALHOST+'#product/Cup Handles" ng-click="reloadData();"><i class=""></i> Handles</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Khuti" ng-click="reloadData();"><i class=""></i> Pegs/Khunti</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Lock" ng-click="reloadData();"><i class=""></i> Lock</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Channel" ng-click="reloadData();"><i class=""></i> Drawer Channel</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Tower Bolt" ng-click="reloadData();"><i class=""></i> Tower Bolt</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Door Catcher" ng-click="reloadData();"><i class=""></i> Door Catcher</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Socket" ng-click="reloadData();"><i class=""></i> Socket</a> </li> </ul> </li> <li class="dropdown" onmouseover="openDropdown(this)" onmouseout="closeDropdown(this)"> <a href="" class="dropdown-toggle nav-opposite" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown"> <i class=""></i> Glass Fitting </a> <ul class="dropdown-menu dropdown-danger"> <li> <a href="'+LOCALHOST+'#product/Glass Handles" ng-click="reloadData();"><i class=""></i> Handles</a> </li> <li> <a href="'+LOCALHOST+'#product/Glass Bracket" ng-click="reloadData();"><i class=""></i> Glass Bracket</a> </li> <li> <a href="'+LOCALHOST+'#product/Glass Pivot" ng-click="reloadData();"><i class=""></i> Glass Pivot</a> </li> <li> <a href="'+LOCALHOST+'#product/Glass Stand" ng-click="reloadData();"><i class=""></i> '+
  //  'Glass Stand</a> </li> <li> <a href="'+LOCALHOST+'#product/Glass Corner" ng-click="reloadData();"><i class=""></i> Glass Corner</a> </li> <li> <a href="'+LOCALHOST+'#product/Khuti" ng-click="reloadData();"><i class=""></i> Glass Knob</a> </li> </ul> </li> <li class="dropdown" onmouseover="openDropdown(this)" onmouseout="closeDropdown(this)"> <a href="" class="dropdown-toggle nav-opposite" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown"> <i class=""></i> Furniture </a> <ul class="dropdown-menu dropdown-danger"> <li> <a href="'+LOCALHOST+'#product/Furniture Sofa Leg" ng-click="reloadData();"><i class=""></i> Sofa Leg</a> </li> <li> <a href="'+LOCALHOST+'#product/Furniture Drawer Fitting" ng-click="reloadData();"><i class=""></i> Drawer Fitting</a> </li> <li> <a href="'+LOCALHOST+'#product/Furniture Cable Manager" ng-click="reloadData();"><i class=""></i> Cable Manager</a> </li> <li> <a href="'+LOCALHOST+'#product/Furniture Curten Bracket" ng-click="reloadData();"><i class=""></i> Curten Bracket</a> </li> </ul> </li> <li> <a href="'+LOCALHOST+'#product/Decoratives" ng-class="{\'nav-opposite\':isHome!=true}" class="nav-opposite"> Decoratives</a> </li> <li class="dropdown userIcon" id="userIcon"> <a class="dropdown-toggle nav-opposite" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown" style="margin-left :7px;"> <!-- <a href="javascript:void(0)" style="margin-left :7px;"> --> <i class="fa fa-user nav-opposite" ng-class="{\'nav-opposite\':isHome!=true}"></i> '+
  //  '</a> <ul class="dropdown-menu dropdown-danger" id="userTools"> <li> <div class="userToolInfo"> <a href="'+LOCALHOST+'#my/profile"> <div class="userToolName"> </div> <div id="userToolEmail">akash@123.com</div> </a> </div> <hr> </li> <li> <a href="'+LOCALHOST+'#my/orders" ng-click="reloadData();"><i class=""></i> My Orders</a> </li> <li> <a href="" ng-click="logOut()">Log Out</a> </li> </ul> <!-- <div class="userTools" id="userTools" style="display: none;"> <div class="arrow-up"></div> <div class="userToolInfo"> <a href="'+LOCALHOST+'#my/profile" class="dropdown-product-link"> <div class="userToolName"> </div> <div id="userToolEmail"> </div> </a> </div> <hr> <div class="userToolOrders"> <a href="'+LOCALHOST+'#my/orders" class="dropdown-product-link">My Orders</a> </div> <hr> <div class="userToolLogOut"> <a href="" ng-click="logOut()" class="dropdown-product-link">Log Out</a> </div> </div> --> </li> <li> <a href="'+LOCALHOST+'#cart" style="margin-left :7px;"> <div><i class="fa fa-cart-arrow-down nav-opposite" ng-class="{\'nav-opposite\':isHome!=true}"></i></div> </a> </li> <li> <span ng-class="{\'nav-opposite\':isHome!=true}" id="cartValue" class="nav-opposite"></span> </li> </ul> </div> </div> <!-- /.navbar-collapse --> </nav> <div class="container"> <!-- Log In | Register modal --> <div class="modal fade login" id="loginModal"> <div class="modal-dialog login animated"> <div class="modal-content"> <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> '+
  //  '<h4 class="modal-title" style="font-family: inherit;">Login</h4> </div> <div class="modal-body ng-scope" ng-controller="loginAction"> <div class="box"> <div class="content"> <div class="error"></div> <div class="form loginBox"> <form method="post" accept-charset="UTF-8" class="ng-pristine ng-valid"> <input id="email" value="" ng-model="login.email" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="text" placeholder="Email" name="email" style="outline: none;"> <input id="password" value="" ng-model="login.password" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="password" placeholder="Password" name="password" style="outline: none;"> <input class="btn btn-default btn-login" type="button" value="Login" ng-click="userLogin()"> <!-- <div class="facebook-login-content"> <span style="text-align: center;margin-left: 48%;font-size: 1.4vw;">Or</span> <button type="button" value="Log In With Facebook" ng-click="logInFacebook()" style="border: 0;color: white;border-radius: 2px;background: rgba(0, 0, 255, 0.73);width: 100%;font-size: 1.2vw;padding: 13px;outline:none;">Log In With Facebook</button> </div> --> <span id="loginResponse"></span> </form> </div> </div> </div> <div class="box ng-scope" ng-controller="registerAction"> <div class="content registerBox" style="display:none;"> <div class="form"> <form method="post" html="{:multipart=>true}" data-remote="true" accept-charset="UTF-8" class="ng-pristine ng-valid">'+
  //  ' <input id="email" ng-model="register.email" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="text" placeholder="Email" name="email"> <input id="password" ng-model="register.mobile" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="text" placeholder="Mobile" name="mobile"> <input id="password" ng-model="register.password" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="password" placeholder="Password" name="password"> <input id="password_confirmation" ng-model="register.confirmPassword" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="password" placeholder="Repeat Password" name="password_confirmation"> <input class="btn btn-default btn-register" ng-click="userRegister()" type="submit" value="Create account" id="registerButton" name="commit"> <input class="login-form-control ng-pristine ng-untouched ng-valid ng-empty ng-hide" type="text" placeholder="OTP" ng-show="OTP == true" ng-model="register.otp"> <input class="btn btn-default btn-register ng-hide" ng-show="OTP == true" ng-click="submitOTP()" type="submit" value="Submit OTP" id="otpButton" name="commit"> <span id="registerResponse"></span> </form> </div> </div> </div> </div> <div class="modal-footer"> <div class="forgot login-footer"> <span>Looking to <a href="javascript: showRegisterForm();">create an account</a> ?</span> </div> <div class="forgot register-footer" style="display:none"> <span>Already have an account?</span>'+
  //  ' <a href="javascript: showLoginForm();">Login</a> </div> </div> </div> </div> </div> </div> <!-- Modal ends here --> <div> <div class="failed-order-content"> <div class="failed-order-message"> Order Failed </div> <div class="failed-order-icon"><img src="'+LOCALHOST+'assets/img/orderFailed.png" width="100%" height="100%"></div> <div class="failed-order-reason"> <p>Due to some error your order can not be processed right now.</p> </div> <div class="order-failed-cart"> <a href="'+LOCALHOST+'#cart" style="opacity:1;"> <button value="To Cart" class="order-failed-button">Go To Cart</button></a> </div> <div class="failed-order-note"><b>Note:</b> In case of any query or inconvenience feel free to inform us at query@akratiindia.com.</div> </div> </div> </div> <footer class="footer footer-big footer-color-black" data-color="black"> <div class="container"> <div class="row"> <div class="col-md-2 col-sm-3"> <div class="info"> <h5 class="title">Company</h5> <nav> <ul> <li> <a href="'+LOCALHOST+'#/">Home</a> </li> <li> <a href="'+LOCALHOST+'#aboutUs">About Us</a> </li> </ul> </nav> </div> </div> <div class="col-md-3 col-md-offset-1 col-sm-3"> <div class="info"> <h5 class="title"> Help and Support</h5> <nav> <ul> <li> <a href="'+LOCALHOST+'#contactUs">Contact Us</a> </li> <li> <a href="'+LOCALHOST+'#howWeWork">How it works</a> </li> <li> <a href="'+LOCALHOST+'#termsConditions">Terms Of Use</a> </li> <li> <a href="'+LOCALHOST+'#companyPolicy">Privacy Policy</a> '+
  //  '</li> <li> <a href="'+LOCALHOST+'#moneyBack">Money Back</a> </li> </ul> </nav> </div> </div> <div class="col-md-3 col-sm-3"> </div> <div class="col-md-2 col-md-offset-1 col-sm-3"> <div class="info"> <h5 class="title">Follow us on</h5> <nav> <ul> <li> <a href="https://www.facebook.com/Akrati-India-156038181607620/" class="btn btn-social btn-facebook btn-simple"> <i class="fa fa-facebook-square"></i> Facebook </a> </li> <li> <a href="https://www.linkedin.com/company-beta/13346708/admin/updates/" class="btn btn-social btn-twitter btn-simple"> <i class="fa fa-linkedin"></i> LinkedIn </a> </li> <li> <a href="https://business.google.com/b/107704939304271578825/dashboard/l/18079967296478228732?hl=en-GB" class="btn btn-social btn-reddit btn-simple"> <i class="fa fa-google-plus-square"></i> Google+ </a> </li> </ul> </nav> </div> </div> </div> <hr> <div class="copyright"> © <script> document.write(new Date().getFullYear()) </script>2017 Akratiindia </div> </div> </footer>'+
  //  ' <!-- core js files --> <script src="'+LOCALHOST+'assets/js/spin.min.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/jquery.min.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/bootstrap.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/login-register.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/bootstrap-notify.min.js" type="text/javascript"></script> <script type="text/javascript" src="'+LOCALHOST+'slick/slick.js"></script> <!-- js library for devices recognition --> <script type="text/javascript" src="'+LOCALHOST+'assets/js/modernizr.js"></script> <!-- script for google maps --> <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script> <!-- script for image slider--> <!-- file where we handle all the script from the Gaia - Bootstrap Template --> <script type="text/javascript" src="'+LOCALHOST+'assets/js/gaia.js"></script> <script src="'+LOCALHOST+'assets/angular/angular.min.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/angular/ngStorage.min.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/angular/angular-route.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/angular/main.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/angular/user.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/bootstrap-datepicker.js"></script> </body></html>';
  //   return html;

    var html = '<!DOCTYPE html><html lang="en" class="js touch"><head><style type="text/css">@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate){display:none !important;}ng\:form{display:block;}.ng-animate-shim{visibility:hidden;}.ng-anchor{position:absolute;}</style> <meta charset="utf-8"/> <link rel="apple-touch-icon" sizes="76x76" href="' +LOCALHOST+ 'assets/img/apple-icon.png"> <link rel="icon" type="image/png" sizes="96x96" href="'+LOCALHOST+'assets/img/logo.png"> <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">'+
     '<title>akratiindia</title> <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"> <link href="'+LOCALHOST+'assets/css/bootstrap.css" rel="stylesheet"> <link href="'+LOCALHOST+'assets/css/gaia.css" rel="stylesheet"> <link href="'+LOCALHOST+'assets/css/login-register.css" rel="stylesheet"> <link href="'+LOCALHOST+'assets/css/animate.css" rel="stylesheet"> <link rel="stylesheet" type="text/css" href="'+LOCALHOST+'slick/slick.css"> <link rel="stylesheet" type="text/css" href="'+LOCALHOST+'slick/slick-theme.css">'+
     ' <link rel="stylesheet" type="text/css" href="'+LOCALHOST+'assets/css/roboto.css"> <link rel="stylesheet" type="text/css" href="'+LOCALHOST+'assets/css/dhtmlx.css"> <script src="'+LOCALHOST+'assets/js/dhtmlx.js"></script> <!-- Fonts and icons--> <link href="https://fonts.googleapis.com/css?family=Cambo|Poppins:400,600" rel="stylesheet" type="text/css"> <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet"> <link rel="stylesheet" href="'+LOCALHOST+'assets/css/bootstrap-datepicker.css"> <link href="'+LOCALHOST+'assets/css/fonts/pe-icon-7-stroke.css" rel="stylesheet"> <style type="text/css"></style>'+
     '</head> <body ng-app="main" ng-controller="loginCheck" id="body" class="ng-scope"> <nav class="main-header navbar navbar-default navbar-transparent navbar-fixed-top ng-scope" color-on-scroll="200" ng-class="{\'nav-opposite\':isHome!=true}" ng-controller="showProducts"> <!-- if you want to keep the navbar hidden you can add this class to the navbar "navbar-burger"--> <div class="container"> <!-- <div class="container" style="width:1268px;"> --> <div class="navbar-header"> <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar bar1" ng-class="{\'navbar-toggle-color\': isHome!=true}"></span> <span class="icon-bar bar2" ng-class="{\'navbar-toggle-color\': isHome!=true}"></span> <span class="icon-bar bar3" ng-class="{\'navbar-toggle-color\': isHome!=true}"></span> </button> <a href="'+LOCALHOST+'index.html" class="navbar-brand opaque" id="navbar-logo"> <img src="'+LOCALHOST+'assets/img/logo.png" id="topHeaderImage"> <span id="topHeaderLogo"> '+
     '<span class="logoAkrati" style="color: #0075a6;">akrati</span><span class="logoIndia" style="color: #991014;">india</span> </span> </a> </div> <div class="collapse navbar-collapse"> <ul class="nav navbar-nav navbar-right navbar-uppercase" style="margin-top:13px;"> <li class="li-search"> <div class="search-box"> <div class="container-1"> <a href="'+LOCALHOST+'#product/search="><span class="icon"><i class="fa fa-search"></i></span></a> <input type="search" id="search" my-enter="searchPressed();" ng-model="searchQuery" placeholder="Search..." class="ng-pristine ng-untouched ng-valid ng-empty"> </div> </div> </li> <li class="dropdown" onmouseover="openDropdown(this)" onmouseout="closeDropdown(this)"> <a href="" class="dropdown-toggle" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown"> <i class=""></i> Door Fitting </a> <ul class="dropdown-menu dropdown-danger"> <li> <a href="'+LOCALHOST+'#product/handles" ng-click="reloadData();"><i class=""></i> Handles</a>'+
      '</li> <li> <a href="'+LOCALHOST+'#product/Khunti" ng-click="reloadData();"><i class=""></i>Pegs/Khunti</a> </li> <li> <a href="'+LOCALHOST+'#product/Tower Bolt" ng-click="reloadData();"><i class=""></i> Tower Bolt</a> </li> <li> <a href="'+LOCALHOST+'#product/AL-Drop" ng-click="reloadData();"><i class=""></i> AL-Drop</a> </li> <li> <a href="'+LOCALHOST+'#product/Mortise" ng-click="reloadData();"><i class=""></i> Mortise</a> </li> <li> <a href="'+LOCALHOST+'#product/Bathroom Latch" ng-click="reloadData();"><i class=""></i> Bathroom Latch</a> </li> <li> <a href="'+LOCALHOST+'#product/Door Stopper" ng-click="reloadData();"><i class=""></i>Door Stopper</a> </li> <li> <a href="'+LOCALHOST+'#product/Locks" ng-click="reloadData();"><i class=""></i> Locks</a> </li> <li> <a href="'+LOCALHOST+'#product/Door Knocker" ng-click="reloadData();"><i class=""></i> Door Knocker</a> </li> <li> <a href="'+LOCALHOST+'#product/Door Kit" ng-click="reloadData();"><i class=""></i> Door Kit</a> </li> </ul> </li> <li class="dropdown" onmouseover="openDropdown(this)" onmouseout="closeDropdown(this)">'+
      '<a href="" class="dropdown-toggle" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown"> <i class=""></i> Cub Board Fitting </a> <ul class="dropdown-menu dropdown-danger"> <li> <a href="'+LOCALHOST+'#product/Cup Handles" ng-click="reloadData();"><i class=""></i> Handles</a> </li> <li> '+
     '<a href="'+LOCALHOST+'#product/Cup Khuti" ng-click="reloadData();"><i class=""></i> Pegs/Khunti</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Lock" ng-click="reloadData();"><i class=""></i> Lock</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Channel" ng-click="reloadData();"><i class=""></i> Drawer Channel</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Tower Bolt" ng-click="reloadData();"><i class=""></i> Tower Bolt</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Door Catcher" ng-click="reloadData();"><i class=""></i> Door Catcher</a> </li> <li> <a href="'+LOCALHOST+'#product/Cup Socket" ng-click="reloadData();"><i class=""></i> Socket</a> </li> </ul> </li> <li class="dropdown" onmouseover="openDropdown(this)" onmouseout="closeDropdown(this)"> <a href="" class="dropdown-toggle" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown"> <i class=""></i> Glass Fitting </a> <ul class="dropdown-menu dropdown-danger"> <li> <a href="'+LOCALHOST+'#product/Glass Handles" ng-click="reloadData();"><i class=""></i> Handles</a> </li> <li>'+
      '<a href="'+LOCALHOST+'#product/Glass Bracket" ng-click="reloadData();"><i class=""></i> Glass Bracket</a> </li> <li> <a href="'+LOCALHOST+'#product/Glass Pivot" ng-click="reloadData();"><i class=""></i> Glass Pivot</a> </li> <li> <a href="'+LOCALHOST+'#product/Glass Stand" ng-click="reloadData();"><i class=""></i> Glass Stand</a> </li> <li> <a href="'+LOCALHOST+'#product/Glass Corner" ng-click="reloadData();"><i class=""></i> Glass Corner</a> </li> <li> <a href="'+LOCALHOST+'#product/Khuti" ng-click="reloadData();"><i class=""></i> Glass Knob</a> </li> </ul> </li> <li class="dropdown" onmouseover="openDropdown(this)" onmouseout="closeDropdown(this)"> <a href="" class="dropdown-toggle" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown"> <i class=""></i> Furniture </a> <ul class="dropdown-menu dropdown-danger"> <li> <a href="'+LOCALHOST+'#product/Furniture Sofa Leg" ng-click="reloadData();"><i class=""></i> Sofa Leg</a> </li> <li> <a href="'+LOCALHOST+'#product/Furniture Drawer Fitting" ng-click="reloadData();"><i class=""></i> Drawer Fitting</a>'+
       '</li> <li> <a href="'+LOCALHOST+'#product/Furniture Cable Manager" ng-click="reloadData();"><i class=""></i> Cable Manager</a> </li> <li> <a href="'+LOCALHOST+'#product/Furniture Curten Bracket" ng-click="reloadData();"><i class=""></i> Curten Bracket</a> </li> </ul> </li> <li> <a href="'+LOCALHOST+'#product/Decoratives" ng-class="{\'nav-opposite\':isHome!=true}" class=""> Decoratives</a> </li> <li class="dropdown userIcon" id="userIcon"> <a class="dropdown-toggle" ng-class="{\'nav-opposite\':isHome!=true}" data-toggle="dropdown" style="margin-left :7px;"> <!-- <a href="javascript:void(0)" style="margin-left :7px;"> --> <i class="fa fa-user" ng-class="{\'nav-opposite\':isHome!=true}"></i> </a> <ul class="dropdown-menu dropdown-danger" id="userTools"> <li> <div class="userToolInfo"> <a href="'+LOCALHOST+'#my/profile"> <div class="userToolName"> </div> <div id="userToolEmail"></div> </a> </div> <hr> </li> <li> <a href="'+LOCALHOST+'#my/orders" ng-click="reloadData();"><i class=""></i> My Orders</a> </li> <li> '+
       '<a href="" ng-click="logOut()">Log Out</a> </li> </ul> <!-- <div class="userTools" id="userTools" style="display: none;"> <div class="arrow-up"></div> <div class="userToolInfo"> <a href="'+LOCALHOST+'#my/profile" class="dropdown-product-link"> <div class="userToolName"> </div> <div id="userToolEmail"> </div> </a> </div> <hr> <div class="userToolOrders"> <a href="'+LOCALHOST+'#my/orders" class="dropdown-product-link">My Orders</a> </div> <hr> <div class="userToolLogOut"> <a href="" ng-click="logOut()" class="dropdown-product-link">Log Out</a> </div> </div> --> </li> <li> <a href="'+LOCALHOST+'#cart" style="margin-left :7px;"> <div><i class="fa fa-cart-arrow-down" ng-class="{\'nav-opposite\':isHome!=true}"></i></div> </a> </li> <li> <span ng-class="{\'nav-opposite\':isHome!=true}" id="cartValue" class=""></span> </li> </ul> </div> </div> <!-- /.navbar-collapse --> </nav><div class="container"> <!-- Log In | Register modal --> <div class="modal fade login" id="loginModal"> <div class="modal-dialog login animated"> <div class="modal-content"> <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> '+
     '<h4 class="modal-title" style="font-family: inherit;">Login</h4> </div> <div class="modal-body ng-scope" ng-controller="loginAction"> <div class="box"> <div class="content"> <div class="error"></div> <div class="form loginBox"> <form method="post" accept-charset="UTF-8" class="ng-pristine ng-valid"> <input id="email" value="" ng-model="login.email" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="text" placeholder="Email" name="email" style="outline: none;"> <input id="password" value="" ng-model="login.password" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="password" placeholder="Password" name="password" style="outline: none;"> <input class="btn btn-default btn-login" type="button" value="Login" ng-click="userLogin()"> <!-- <div class="facebook-login-content"> <span style="text-align: center;margin-left: 48%;font-size: 1.4vw;">Or</span> <button type="button" value="Log In With Facebook" ng-click="logInFacebook()" style="border: 0;color: white;border-radius: 2px;background: rgba(0, 0, 255, 0.73);width: 100%;font-size: 1.2vw;padding: 13px;outline:none;">Log In With Facebook</button> </div> --> <span id="loginResponse"></span> </form> </div> </div> </div> <div class="box ng-scope" ng-controller="registerAction"> <div class="content registerBox" style="display:none;"> <div class="form"> <form method="post" html="{:multipart=>true}" data-remote="true" accept-charset="UTF-8" class="ng-pristine ng-valid">'+
     ' <input id="email" ng-model="register.email" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="text" placeholder="Email" name="email"> <input id="password" ng-model="register.mobile" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="text" placeholder="Mobile" name="mobile"> <input id="password" ng-model="register.password" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="password" placeholder="Password" name="password"> <input id="password_confirmation" ng-model="register.confirmPassword" class="login-form-control ng-pristine ng-untouched ng-valid ng-empty" type="password" placeholder="Repeat Password" name="password_confirmation"> <input class="btn btn-default btn-register" ng-click="userRegister()" type="submit" value="Create account" id="registerButton" name="commit"> <input class="login-form-control ng-pristine ng-untouched ng-valid ng-empty ng-hide" type="text" placeholder="OTP" ng-show="OTP == true" ng-model="register.otp"> <input class="btn btn-default btn-register ng-hide" ng-show="OTP == true" ng-click="submitOTP()" type="submit" value="Submit OTP" id="otpButton" name="commit"> <span id="registerResponse"></span> </form> </div> </div> </div> </div> <div class="modal-footer"> <div class="forgot login-footer"> <span>Looking to <a href="javascript: showRegisterForm();">create an account</a> ?</span> </div> <div class="forgot register-footer" style="display:none"> <span>Already have an account?</span>'+
     ' <a href="javascript: showLoginForm();">Login</a> </div> </div> </div> </div> </div> </div> <!-- Modal ends here --> <div> <div class="failed-order-content"> <div class="failed-order-message"> Order Failed </div> <div class="failed-order-icon"><img src="'+LOCALHOST+'assets/img/orderFailed.png" width="100%" height="100%"></div> <div class="failed-order-reason"> <p>Due to some error your order can not be processed right now.</p> </div> <div class="order-failed-cart"> <a href="'+LOCALHOST+'#cart" style="opacity:1;"> <button value="To Cart" class="order-failed-button">Go To Cart</button></a> </div> <div class="failed-order-note"><b>Note:</b> In case of any query or inconvenience feel free to inform us at query@akratiindia.com.</div> </div> </div> </div> <footer class="footer footer-big footer-color-black" data-color="black"> <div class="container"> <div class="row"> <div class="col-md-2 col-sm-3"> <div class="info"> <h5 class="title">Company</h5> <nav> <ul> <li> <a href="'+LOCALHOST+'#/">Home</a> </li> <li> <a href="'+LOCALHOST+'#aboutUs">About Us</a> </li> </ul> </nav> </div> </div> <div class="col-md-3 col-md-offset-1 col-sm-3"> <div class="info"> <h5 class="title"> Help and Support</h5> <nav> <ul> <li> <a href="'+LOCALHOST+'#contactUs">Contact Us</a> </li> <li> <a href="'+LOCALHOST+'#howWeWork">How it works</a> </li> <li> <a href="'+LOCALHOST+'#termsConditions">Terms Of Use</a> </li> <li> <a href="'+LOCALHOST+'#companyPolicy">Privacy Policy</a> '+
     '</li> <li> <a href="'+LOCALHOST+'#moneyBack">Money Back</a> </li> </ul> </nav> </div> </div> <div class="col-md-3 col-sm-3"> </div> <div class="col-md-2 col-md-offset-1 col-sm-3"> <div class="info"> <h5 class="title">Follow us on</h5> <nav> <ul> <li> <a href="https://www.facebook.com/Akrati-India-156038181607620/" class="btn btn-social btn-facebook btn-simple"> <i class="fa fa-facebook-square"></i> Facebook </a> </li> <li> <a href="https://www.linkedin.com/company-beta/13346708/admin/updates/" class="btn btn-social btn-twitter btn-simple"> <i class="fa fa-linkedin"></i> LinkedIn </a> </li> <li> <a href="https://business.google.com/b/107704939304271578825/dashboard/l/18079967296478228732?hl=en-GB" class="btn btn-social btn-reddit btn-simple"> <i class="fa fa-google-plus-square"></i> Google+ </a> </li> </ul> </nav> </div> </div> </div> <hr> <div class="copyright"> © <script> document.write(new Date().getFullYear()) </script>2017 Akratiindia </div> </div> </footer>'+
     ' <!-- core js files --> <script src="'+LOCALHOST+'assets/js/spin.min.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/jquery.min.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/bootstrap.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/login-register.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/bootstrap-notify.min.js" type="text/javascript"></script> <script type="text/javascript" src="'+LOCALHOST+'slick/slick.js"></script> <!-- js library for devices recognition --> <script type="text/javascript" src="'+LOCALHOST+'assets/js/modernizr.js"></script> <!-- script for google maps --> <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script> <!-- script for image slider--> <!-- file where we handle all the script from the Gaia - Bootstrap Template --> <script type="text/javascript" src="'+LOCALHOST+'assets/js/gaia.js"></script> <script src="'+LOCALHOST+'assets/angular/angular.min.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/angular/ngStorage.min.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/angular/angular-route.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/angular/main.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/angular/user.js" type="text/javascript"></script> <script src="'+LOCALHOST+'assets/js/bootstrap-datepicker.js"></script> </body></html>';
      return html;


}



}
